// GENERATED by greenforge v0.1 — CHARACTERIZATION tests.
// Each assertion pins the CURRENT output of the function. Valid iff current behaviour is the intended spec
// (always true for a pure content-addresser/serializer; REVIEW for business logic). Regenerate if behaviour
// changes intentionally. greenforge confirmed every assertion below kills a real surviving mutant.
// ⚑ REPAIRED 2026-08-18: the original pins were produced via JSON.stringify, which DROPS keys whose
// value is undefined — so they pinned a shape the function can never emit (cluster() groups records
// by r.hash; bare strings give every element hash: undefined, an own property). A characterization
// that cannot match its own re-run is not a pin, it is a red light wired permanently on.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as M from './sieve.mjs';

test('greenforge · cluster characterization', () => {
  assert.deepEqual(M["cluster"](""), []);
  assert.deepEqual(M["cluster"]("a"), [{ hash: undefined, members:["a"]}]);
  assert.deepEqual(M["cluster"]("abc"), [{ hash: undefined, members:["a","b","c"]}]);
  assert.deepEqual(M["cluster"]("Zürich"), [{ hash: undefined, members:["Z","ü","r","i","c","h"]}]);
  assert.deepEqual(M["cluster"]("0"), [{ hash: undefined, members:["0"]}]);
  assert.deepEqual(M["cluster"]("10"), [{ hash: undefined, members:["1","0"]}]);
  assert.deepEqual(M["cluster"]("2"), [{ hash: undefined, members:["2"]}]);
  assert.throws(() => M["cluster"](0));
  assert.throws(() => M["cluster"](1));
  assert.throws(() => M["cluster"](-1));
  assert.throws(() => M["cluster"](2));
  assert.throws(() => M["cluster"](10));
  assert.throws(() => M["cluster"](-0.5));
  assert.throws(() => M["cluster"](1.5));
  assert.throws(() => M["cluster"](100));
  assert.throws(() => M["cluster"](0.6180339887));
  assert.throws(() => M["cluster"](true));
  assert.throws(() => M["cluster"](false));
  assert.throws(() => M["cluster"](null));
  assert.deepEqual(M["cluster"]([]), []);
  assert.deepEqual(M["cluster"]([1,2,3]), [{ hash: undefined, members:[1,2,3]}]);
  assert.deepEqual(M["cluster"]([10,2,1]), [{ hash: undefined, members:[10,2,1]}]);
  assert.throws(() => M["cluster"]({"a":1}));
  assert.throws(() => M["cluster"]({"a":2}));
  assert.throws(() => M["cluster"]({"n":10}));
  assert.throws(() => M["cluster"]({"n":2}));
  assert.throws(() => M["cluster"](1));
  assert.throws(() => M["cluster"](0));
  assert.throws(() => M["cluster"](2));
  assert.throws(() => M["cluster"](3));
  assert.throws(() => M["cluster"](4));
  assert.throws(() => M["cluster"](-1));
  assert.throws(() => M["cluster"](5));
  assert.throws(() => M["cluster"](128));
  assert.throws(() => M["cluster"](127));
  assert.throws(() => M["cluster"](129));
  assert.throws(() => M["cluster"](32));
  assert.throws(() => M["cluster"](31));
  assert.throws(() => M["cluster"](33));
  assert.throws(() => M["cluster"](65));
  assert.throws(() => M["cluster"](64));
  assert.throws(() => M["cluster"](66));
  assert.throws(() => M["cluster"](16));
  assert.throws(() => M["cluster"](15));
  assert.throws(() => M["cluster"](17));
  assert.throws(() => M["cluster"](13));
  assert.throws(() => M["cluster"](12));
  assert.throws(() => M["cluster"](14));
  assert.throws(() => M["cluster"](8));
  assert.throws(() => M["cluster"](7));
  assert.throws(() => M["cluster"](9));
  assert.throws(() => M["cluster"](0.7));
  assert.throws(() => M["cluster"](-0.30000000000000004));
  assert.throws(() => M["cluster"](1.7));
});

test('greenforge · contentHash characterization', () => {
  assert.deepEqual(M["contentHash"](""), "ab3e7c0b92ca2f0ecb72770f0c66c024");
  assert.deepEqual(M["contentHash"]("a"), "1a80b1b369d6c81319d549e25f61146c");
  assert.deepEqual(M["contentHash"]("abc"), "1cc93dbce5d5c79f54bb0031268bd56b");
  assert.deepEqual(M["contentHash"]("Zürich"), "946df6c0423a7abd06c9daef7b5fb5d2");
  assert.deepEqual(M["contentHash"]("0"), "64f08f61ddb08104d5a173cde06f4cc7");
  assert.deepEqual(M["contentHash"]("10"), "dd5b31b43accca0c21f96a9269511666");
  assert.deepEqual(M["contentHash"]("2"), "3cce455f72e696182137a844e472e99e");
  assert.deepEqual(M["contentHash"](0), "64f08f61ddb08104d5a173cde06f4cc7");
  assert.deepEqual(M["contentHash"](1), "551f758f9ad3651eea1d277442d0d09b");
  assert.deepEqual(M["contentHash"](-1), "7f872a6a4d2e3208ec096b550ee86d00");
  assert.deepEqual(M["contentHash"](2), "3cce455f72e696182137a844e472e99e");
  assert.deepEqual(M["contentHash"](10), "dd5b31b43accca0c21f96a9269511666");
  assert.deepEqual(M["contentHash"](-0.5), "14d6dbe1e14cdfaa7f74388d6e347d74");
  assert.deepEqual(M["contentHash"](1.5), "1386817d6e13615bf6e46f5647685b30");
  assert.deepEqual(M["contentHash"](100), "f642f01ef7488166d63bd9cccc73a083");
  assert.deepEqual(M["contentHash"](0.6180339887), "22cab03e62e0b8c23ba1a2d219152872");
  assert.deepEqual(M["contentHash"](true), "663d84619952962373868d4f8720f1e1");
  assert.deepEqual(M["contentHash"](false), "fed74ee71d4cf44cf0a695b7c5252b53");
  assert.deepEqual(M["contentHash"](null), "ab3e7c0b92ca2f0ecb72770f0c66c024");
  assert.deepEqual(M["contentHash"]([]), "c570341f3751ba9dfd7f4b20248e892d");
  assert.deepEqual(M["contentHash"]([1,2,3]), "30ee39356f94afa4dd064b2783efad5d");
  assert.deepEqual(M["contentHash"]([10,2,1]), "91741a416e9b7eb40d17c61cf5c9ebe4");
  assert.deepEqual(M["contentHash"]({"a":1}), "09a1904541f5f17f37a8a9f45a3fff68");
  assert.deepEqual(M["contentHash"]({"a":2}), "30bd0709df4db4f6248b483532c34fa5");
  assert.deepEqual(M["contentHash"]({"n":10}), "d02d1a8238591bdda94517a4803e78e3");
  assert.deepEqual(M["contentHash"]({"n":2}), "dd3318e44103348bb7a3880493fc3b62");
  assert.deepEqual(M["contentHash"](1), "551f758f9ad3651eea1d277442d0d09b");
  assert.deepEqual(M["contentHash"](0), "64f08f61ddb08104d5a173cde06f4cc7");
  assert.deepEqual(M["contentHash"](2), "3cce455f72e696182137a844e472e99e");
  assert.deepEqual(M["contentHash"](3), "144c23edfeb3a57f98c45c7ba9439b55");
  assert.deepEqual(M["contentHash"](4), "720f235be8627876cfa0ff00b9d0842e");
  assert.deepEqual(M["contentHash"](-1), "7f872a6a4d2e3208ec096b550ee86d00");
  assert.deepEqual(M["contentHash"](5), "058af5e39d0e5cd154b78da5db83afd5");
  assert.deepEqual(M["contentHash"](128), "48013d22cf0b3fc24386dbd6e6a9ad3b");
  assert.deepEqual(M["contentHash"](127), "cea7fab630f8958577c929bb6504b195");
  assert.deepEqual(M["contentHash"](129), "c71ed227fdd0ca0c656530b591f5f4d4");
  assert.deepEqual(M["contentHash"](32), "c3d2402071fe9fbb49245cba2805f622");
  assert.deepEqual(M["contentHash"](31), "45b0a5c87a81e8fbe2f464eb19890724");
  assert.deepEqual(M["contentHash"](33), "c64bd97e8e4b51ecf73bc3653b12ba94");
  assert.deepEqual(M["contentHash"](65), "682a2944fbf978118872a7810182ba92");
  assert.deepEqual(M["contentHash"](64), "c2a559b338c3015385c690e212a09508");
  assert.deepEqual(M["contentHash"](66), "5ea5f708cfba718ae76f3794a9bc3648");
  assert.deepEqual(M["contentHash"](16), "e9a54e07fadc0b87141da476d0419e85");
  assert.deepEqual(M["contentHash"](15), "dd72944d7df12f208e5066d2acabd11f");
  assert.deepEqual(M["contentHash"](17), "311ab9440431a940916d5c8cc86f88a0");
  assert.deepEqual(M["contentHash"](13), "173e079b1c3d712a71a7e7fa4ef1d958");
  assert.deepEqual(M["contentHash"](12), "0c410bd66593f74d74d6919354639952");
  assert.deepEqual(M["contentHash"](14), "fdc02e736b32874a37c1819ef0c118f9");
  assert.deepEqual(M["contentHash"](8), "a5236db3830ccc2cf978dcd9c7b3c6c7");
  assert.deepEqual(M["contentHash"](7), "7a21d05d2c0addde9c35c31af77c80b5");
  assert.deepEqual(M["contentHash"](9), "4615252f7e5842c5819c000b09ef2bb6");
  assert.deepEqual(M["contentHash"](0.7), "009c729135550a179c50ce85c894fbfd");
  assert.deepEqual(M["contentHash"](-0.30000000000000004), "ecbf8abf348ac2826b0c00200949ecf1");
  assert.deepEqual(M["contentHash"](1.7), "783909ab55745be94eec15b53d8e7c60");
});
